<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>
<h2 id="authentication">Authentication</h2>

The API can be accessed only with a valid token, which can be generated by the admins in the admin panel. In
order to be able to use the API, provide the token in a GET parameter. If the token is missing or wrong,
then the following error is returned:

<pre><code class="json">{
    "name": "Unauthorized",
    "message": "Api token is required",
    "code": 0,
    "status": 401,
    "type": "yii\\web\\HttpException"
}</code></pre>

<p>When the request is done by a get method the response will be the following.</p>

<pre><code class="json">{
    "name": "Method Not Allowed",
    "message": "Method Not Allowed. This url can only handle the following request methods: POST, HEAD.",
    "code": 0,
    "status": 405,
    "type": "yii\\web\\HttpException"
}</code></pre>

<p>Example URL: </p>
<p><?= Html::a(Url::base(true) . '/api/v2/cities?token=[token]', '/api/v2/cities?token=[token]', ['class' => 'link link--info']) ?></p>

<p>The API accepts images via POST request in multipart form structure.</p>