#!/bin/sh
# MIT © Sindre Sorhus - sindresorhus.com

# git hook to run a command after `git pull` if a specified file was changed
# Run `chmod +x post-merge` to make it executable then put it into `.git/hooks/`.

NOCOLOR='\033[0m'
REDCOLOR='\033[37;41m'

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
    echo "$changed_files" | grep --quiet "$1" && eval "$2" || :
}

check_run package.json 'printf "$REDCOLOR%s$NOCOLOR\n" "package.json has changed. You should run npm install && npm prune"'
check_run npm-shrinkwrap.json 'printf "$REDCOLOR%s$NOCOLOR\n" "npm-shrinkwrap.json has changed. You should run npm install && npm prune"'
check_run composer.lock 'printf "$REDCOLOR%s$NOCOLOR\n" "composer.lock has changed. You should run composer install --prefer-dist"'

# check_run package.json "npm install && npm prune"
# check_run composer.lock "composer install --prefer-dist"
