<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'annual_reports.column1.title' => 'Beszámolók',
    'annual_reports.column2.title' => 'Alapító iratok',
    'annual_reports.column3.title' => 'Támogatások',
    'about.lead' => 'Itt megtalálsz minden hasznos infót a myProjectről.',
    'about.title' => 'Ismerd meg a myProject-t',
    'annual_reports.lead' => 'Ezen az oldalon a myProject Egyesület beszámolói érhetők el.',
    'annual_reports.title' => 'Beszámolók és közhasznúsági jelentések',
    'contact.content' => 'Kérdésed van? Vagy csak megosztanád velünk a véleményed? Írj nekünk!',
    'contact.success_message' => 'Köszönjük, hogy megosztottad velünk véleményed!',
    'contact.title' => 'Lépj velünk kapcsolatba',
    'howitworks.lead' => 'Ha megosztod, megoldod. A myProjectn fogadjuk a köztéri problémákról szóló bejelentéseket, továbbítjuk őket az illetékes hivataloknak,
és a választ közzétesszük.',
    'howitworks.title' => 'Hogyan működik a myProject?',
    'partners.lead' => 'Ők azok, akik támogatnak minket abban, hogy megoldjuk a felmerülő problémákat.',
    'partners.title' => 'Partnereink és támogatóink',
    'section.annual_reports.lead' => 'Éves beszámolóinkat és egyéb jogi dokumentumokat találsz itt.',
    'section.annual_reports.link' => 'Nézd meg a beszámolókat',
    'section.howitworks.lead' => 'Ha megosztod, megoldod. A myProjectn fogadjuk a köztéri problémákról szóló bejelentéseket, továbbítjuk őket az illetékes hivataloknak, és a választ közzétesszük.',
    'section.partners.lead' => 'Ők azok, akik támogatnak minket abban, hogy megoldjuk a felmerülő problémákat',
    'section.partners.link' => 'Nézd meg, kik ők',
    'section.statistics.lead' => 'Kíváncsi vagy, hogy hány bejelentés született eddig településeden? Mik a leggyakoribb problémák?',
    'section.statistics.link' => 'Nézd meg a statisztikákat',
    'section.tos.lead' => 'Minden fontos információt megtalálsz itt, ami az oldal használatához szükséges.',
    'section.tos.link' => 'Olvasd el az adatkezelési tájékoztatót',
    'team.lead1' => 'Csapatunk tagjai gondoskodnak arról, hogy a minél gördülékenyebben menjen a felmerült prombléma megoldása.',
    'team.lead2' => 'Mindig keresünk lelkes önkénteseket!',
    'team.title' => 'Ismerd meg a csapatunk',
];
