<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'this-model-does-not-exists-or-you-dont-have-permission' => 'Vagy nincs jogosultságod ehhez a művelethez, vagy a kért elem nem létezik.',
    'you-dont-have-permission-to-this-page' => 'Nincs jogosultságod ehhez a művelethez.',
    'activity.answer_request' => 'válasz kérése',
    'activity.new_report' => 'új bejelentés kezelése',
    'activity.resolve' => 'bejelentés lezárása',
    'activity.response_request' => 'visszajelzés kérése',
    'create' => 'Ügykezelő hozzáadása',
    'delete' => 'Ügykezelő törlése',
    'delete.message' => 'Valóban törlöd az admint a rendszerből?',
    'grid.summary' => '<div class="summary pull-right">Összesen <b>{totalCount, number}</b> találat, <b>{pageCount, number}</b> oldalon</div>',
    'index.full_name' => 'Név',
    'index.score' => 'Pont',
    'status.active' => 'Aktív',
    'status.inactive' => 'Inaktív',
    'status.super_admin' => 'Szuperadmin',
    'update.password_change' => 'Jelszó módosítás',
    'update.activity' => 'Aktivitás',
    'update.activity_help' => 'Mi is az aktivitási pont?',
    'update.activity_help_1' => 'Az Aktivitás pont egy egyszerű módja annak, hogy visszajelzést adjunk az ügykezelőnek, hogy mennyire aktívan kontribuál a myProject szolgáltatásában.',
    'update.activity_help_2' => 'Minden egyes a rendszerben manuálisan tett aktivitásért kap 1 pontot az ügykezelő.',
    'update.activity_help_3' => 'Mivel bárki foglalkozhat az ügyekkel és gyakran előfordul, hogy egy ügyön több ügykezelő is tevékenykedik, így az egyenlő elbírálás miatt, az egyes aktivitásokat nem súlyoztuk.',
    'update.activity_score' => 'Aktivitási pont',
    'update.city' => 'Település',
    'update.pr_page' => 'Pr oldal',
    'update.edit_permission' => 'Jogosultság szerkesztése',
    'update.permission' => 'Jogosultság',
    'update.personal_info' => 'Személyes adatok',
    'update.rank' => 'Ezzel te vagy a(z) {rank}. legaktívabb ügykezelő',
    'update.score' => 'pont',
    'update.success' => 'Sikeresen módosítva.',
    'update.system_info' => 'Rendszer adatok',
    'update.upload' => 'Új kép feltöltése',
    'hotkeys.title' => 'Gyorsbillentyűk',
    'hotkeys.general' => 'Mindenhol működő',
    'hotkeys.general.help' => 'Súgó megjelenítése',
    'hotkeys.report.view' => 'Bejelentés adatlapján',
    'hotkeys.report.view.edit' => 'Szerkesztés',
    'hotkeys.report.view.open' => 'Publikus adatlap megnyitása',
    'hotkeys.report.view.send' => 'Elküldés az illetékesnek',
    'hotkeys.report.view.upload' => 'Válasz feltöltése',
    'hotkeys.report.view.delete' => 'Törlés',
    'hotkeys.report.view.changestatus' => 'Állapot módosítása',
    'hotkeys.report.update' => 'Bejelentés módosítása oldalon',
    'hotkeys.report.update.compare' => 'Összehasonlítás az eredetivel',

    'label.reports' => 'Bejelentések',
    'label.link_to_report' => 'Bejelentés linkje',
    'label.comments_count' => 'Kommentek száma',
    'label.confirm_delete' => 'Biztosan törölni akarod ezt az elemet?',
    'label.update' => 'Módosítás',
    'label.delete' => 'Törlés',
    'label.create' => 'Létrehozás',

    'progress.label' => 'Pénz adományok',
    'progress.label_update' => 'Pénz adomány módosítása: {id}',
    'progress.model.id' => 'ID',
    'progress.model.amount' => 'Mennyiség (Ft)',

    'created_by' => 'Létrehozta',
    'updated_by' => 'Módosította',
    'created_at' => 'Létrehozva',
    'updated_at' => 'Módosítva',
    'update' => 'Módosítás',

    'map-layers' => 'Térképrétegek',
    'map-layers.lat' => 'Szélesség',
    'map-layers.lng' => 'Hosszúság',
    'map-layers.name' => 'Név',
    'map-layers.supported_formats' => 'Fájl(ok) (támogatott formátumok/kiterjesztések: KML, KMZ, JSON)',
    'map-layers.label_update' => 'Térképréteg módosítása: {id}',
    'map-layers.create_update' => 'Térképréteg létrehozása',
];
