<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Recent headlines' => '',
    'appbox.appstore' => '',
    'appbox.googleplay' => '',
    'appbox.content' => '@@@@',
    'footer.cookie.dismiss' => 'Rendben',
    'footer.cookie.allow' => 'Elfogadom',
    'footer.cookie.deny' => 'Elutasítom',
    'footer.cookie.policy' => 'Süti Irányelv',
    'appbox.content1' => 'Töltsd le mobil alkalmazásunkat!',
    'appbox.content1.disabled' => 'Használd a honlapunkat mobilon is!',
    'appbox.content2' => 'Okostelefonod segítségével csupán pár percbe kerül bejelenteni egy problémát és egyszerűen követheted az bejelentéseddel kapcsolatos történéseket.',
    'appbox.title' => 'myProject a mobilodon',
    'error_in_form_submit' => 'A szükséges információk közül egy vagy több hibásan lett megadva.',
    'footer.cookie.learn_more' => 'Többet szeretnék tudni!',
    'footer.cookie.message' => 'A myProject.hu sütiket és hasonló technológiákat használ.',
    'hero-bottom-dual.support.lead' => 'Támogass minket egyszeri, vagy rendszeres adománnyal, hogy segíthessük a bosszantó problémák gyors megoldását!<br><br>1%-os támogatásokhoz adószámunk: ADÓSZÁM',
    'hero-bottom-dual.support.title' => 'Támogasd a myProject működését',
    'hero.know_more' => 'Nézz körül a környékeden',
    'hero.lead' => 'A myProject csapat 2012 óta segít a városlakóknak abban, hogy jelezhessék a kátyúkat, letört szemeteseket, lekopott zebrákat és egyéb közterületi problémákat a lakóhelyükön.',
    'hero.report_problem' => 'Bejelentek egy problémát',
    'hero.support' => 'Támogatom',
    'hero.title' => 'Ha megosztod, megoldod.',
    'login.form.rememberMe' => 'Emlékezz rám',
    'nothing_selected' => 'Nincs beállítva',
    'pagination.link.next' => 'Következő',
    'pagination.link.prev' => 'Előző',
    'pagination.link.last' => 'Utolsó',
    'pagination.link.first' => 'Első',
    'password.old_password_incorrect' => 'A jelenlegi jelszó helytelen',
    'successful_password_update' => 'Sikeresen módosítottad a jelszavad!',
    'successful_profile_update' => 'Sikeresen módosítottad a profilodat!',
    'successful_report_status_change' => 'Sikeresen módosítottad a bejelentés állapotát!',
    'hero.h1' => 'Bajban van a myProject!',
    'hero.text' => 'Most a te segítségedre van szükségünk!',
    'cta.text' => 'A te segítségedre is szükségünk van!',
];
