<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'log-in-with-' => '',
    'log-in-with-facebook' => 'Facebook fiókoddal',
    'log-in-with-google' => 'Google fiókoddal',
    'already-registered?' => 'Már regisztráltál az oldalon?',
    'flash.new-password-successfully-set' => 'Sikeresen beállítottad az új jelszavad!',
    'forgot-password-question' => 'Elfelejtetted a jelszavad?',
    'login-legend' => 'Bejelentkezés',
    'no-accout-yet?' => 'Nincs még fiókod?',
    'or' => 'Vagy',
    'password-recovery-legend' => 'Elfelejtetted a jelszavad?',
    'password-recovery-paragraph' => 'Semmi gond, add meg az e-mail címed és küldünk neked egy linket, amire kattintva meg tudod adni új jelszavad.',
    'password-recovery-success-legend' => 'Nézd meg e-mail fiókod!',
    'password-recovery-success-paragraph' => 'Pillanatokon belül érkezni fog egy levél a megadott e-mail címedre. A levélben találsz egy linket, amire kattintva meg tudsz adni új jelszavat a fiókodhoz.',
    'password-requirements-capital' => 'legyen benne egy nagybetű.',
    'password-requirements-label' => 'A jelszó legyen:',
    'password-requirements-length' => 'legalább 6 karakter hosszú,',
    'password-requirements-number' => 'legyen benne szám,',
    'register-legend' => 'Regisztráció',
    'remember-your-password-question' => 'Eszedbe jutott a jelszavad?',
    'set-new-password.legend' => 'Módosítsd jelszavad!',
    'social-profile-joined-to-account' => '{socialProvider} fiókodat hozzákapcsoltuk myProject profilodhoz.',
    'wrong-username-or-password' => 'Hibás felhasználói név vagy jelszó.',
    'unconfirmed-user' => 'Felhasználói fiókod megerősítésre vár.',
    'successful-registration' => 'Siker! A regisztrációd véglegesítéséhez kattints a linkre, amit a megadott email címre küldtünk neked.',
    'confirm-registration' => 'Regisztráció megerősítése',
    'click-to-confirm' => 'Regisztrációd véglegesítéséhez <a href="{link}">kattints ide</a>,
vagy másold be ezt a linket a böngésződbe: <br>{link}',
    'confirmation-something-went-wrong' => 'Hiba történt a megerősítés során. Próbáld újra, vagy kérj új megerősítő emailt.',
    'confirmation-successful' => 'Sikeresen regisztráltál!',
    'reset-token-something-went-wrong' => 'Hiba történt az új megerősítő email kézbesítése során. Próbáld újra.',
    'token-generated-successfully' => 'Elküldtük a megerősítő emailt.',
    'token-has-been-expired' => 'Sajnos a megerősítő link érvényességi ideje lejárt. <a href="{link}">Új link kéréséhez kattints ide.</a>',
    'reset-button' => 'Újraküldés',
    'register-consent-tick-box-text' => 'Hozzájárulok, hogy a myProject a megadott adataimat kezelje.',
    'register-consent-tick-box-help-text' => 'Elolvastam és megértettem a myProject <a class="link link--info" target="_blank" href="{link}">adatkezelési tájékoztatóját</a>.',
    'error.privacy.policy' => 'Az oldal használatához kérünk, hogy fogadd el az adatkezelési tájékoztatót.',
];
