<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'require-new-password' => 'Kérj új jelszót',
    'show_on_map' => 'Mutasd a térképen',
    'add' => 'Hozzáad',
    'anonymous_report' => 'Névtelen szeretnék maradni',
    'api.generate' => 'Kulcs generálás',
    'api.reset' => 'Kulcs újragenerálás',
    'api.revoke' => 'Kulcs visszavonás',
    'assign' => 'Hozzárendelés',
    'back-to-home' => 'Vissza a nyitóoldalra',
    'cancel' => 'Mégsem',
    'delete' => 'Törlés',
    'draft_report' => 'Elmentem piszkozatként',
    'erase-search-filters' => 'Keresés törlése',
    'i-would-like-new-password' => 'Új jelszót szeretnék',
    'log-in' => 'Lépj be!',
    'login' => 'Bejelentkezés',
    'login2' => 'Belépek',
    'next' => 'Tovább',
    'register' => 'Regisztráció',
    'register!' => 'Regisztrálj!',
    'retry' => 'Próbálja újra',
    'save' => 'Mentés',
    'save_report' => 'Elküldöm a bejelentést',
    'send' => 'Elküld',
    'send2' => 'Elküldöm',
    'set-new-password' => 'Beállítom új jelszónak',
    'submit' => 'Küldés',
    'submit_contact' => 'Üzenet küldése',
    'update' => 'Módosítás',
    'upload' => 'Tallózás',
    'KILL' => 'VÉGLEGES TÖRLÉS',
];
