<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'update.districts_tooltip' => 'Csak akkor állítható nem állapotra, ha előtte minden kerület törlésre kerül.',
    'update.values' => 'Adatok',
    'create' => 'Település hozzáadása',
    'email account authentication failed' => 'Nem sikerült belépni az email fiókba!',
    'email_address-hint' => 'Csak gmail fiókot lehet beállítani. Olyat, amiben be van kapcsolva a "Kevésbé biztonságos alkalmazások hozzáférése" funckió!',
    'grid.adminCount' => 'Ügykezelők',
    'grid.districtCount' => 'Kerületek',
    'grid.reportCount' => 'Bejelentések',
    'grid.streetCount' => 'Utcák',
    'mailServer config not exists' => 'Nincs beállítva levelező szerver!',
    'name_filter.hint' => 'Bejelentések oldalon a szűrőben megjelnő neve ragozva pl.: Budapesten',
    'search.all_statuses' => 'Összes állapot',
    'search.name' => 'Név',
    'search.status' => 'Állapot',
    'status.active' => 'Aktív',
    'status.inactive' => 'Inaktív',
    'update' => 'Település módosítása',
    'update.no_districts' => 'Ennek a településnek nem lehetnek kerületei!',
    'update.tab.districts' => 'Kerületek',
    'update.tab.rules' => 'Szabályok',
    'update.tab.streetgroups' => 'Utcacsoportok',
    'update.tab.streets' => 'Utcák',
];
