<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'report.' => '',
    'report.class.' => '',
    'report.status.' => '',
    'report.class.0' => 'new',
    'report.class.1' => 'editing',
    'report.class.2' => 'waiting-for-info',
    'report.class.3' => 'waiting-for-answer',
    'report.class.4' => 'waiting-for-response',
    'report.class.5' => 'resolved',
    'report.class.6' => 'unresolved',
    'report.class.7' => 'deleted',
    'report.class.8' => 'waiting-for-solution',
    'report.class.9' => 'draft',
    'admin.permission.add' => 'Hozzáadás',
    'admin.permission.admin' => 'Ügykezelők',
    'admin.permission.city' => 'Települések',
    'admin.permission.delete' => 'Törlés',
    'admin.permission.kill' => 'Végleges törlés',
    'admin.permission.full_data_export' => 'Tárolt adatok exportálása',
    'admin.permission.edit' => 'Szerkesztés',
    'admin.permission.institution' => 'Intézmények',
    'admin.permission.report' => 'Bejelentések',
    'admin.permission.pr_page' => 'Pr oldalak',
    'admin.permission.statistics' => 'Statisztika',
    'admin.permission.user' => 'Felhasználók',
    'admin.permission.view' => 'Megtekintés',
    'loader-message' => 'Loading...',
    'no-information' => 'N/A',
    'report.filter.followed' => 'Követett',
    'report.filter.fresh' => 'Friss',
    'report.filter.nearby' => 'Hozzám közeli',
    'report.filter.popular' => 'Kiemelt',
    'report.filter.status.3' => 'Válaszra váró',
    'report.filter.status.4' => 'Megerősítésre váró',
    'report.filter.status.8' => 'Megoldásra váró',
    'report.status.0' => 'Új',
    'report.status.1' => 'Feldolgozás alatt',
    'report.status.2' => 'Kiegészítésre vár',
    'report.status.3' => 'Válaszra vár',
    'report.status.4' => 'Megerősítésre vár',
    'report.status.5' => 'Megoldott',
    'report.status.6' => 'Megoldatlan',
    'report.status.7' => 'Törölt',
    'report.status.8' => 'Megoldásra vár',
    'report.status.9' => 'Piszkozat',
];
