<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'content.status.info.' => '',
    'subject.' => '',
    'admin.new_report.header' => 'Új bejelentés érkezett!',
    'content.status.info.answer' => 'Válasz érkezett az illetékestől  a{reportLabel}re',
    'content.status.info.incoming_email' => 'Válasz érkezett az illetékestől  a{reportLabel}re',
    'content.status.info.close' => 'Ezt a bejelentést megoldatlanul kellett lezárnunk, az indok:<br>"{reason}"<br><br>Köszönjük, hogy segítettél szebbé tenni városod!',
    'content.status.info.delete' => 'A bejelentést Törölt státusszal lezártuk. Ennek oka az lehet, hogy
                                    <ul>
                                        <li>már van erről a problémáról egy vagy több bejelentés,</li>
                                        <li>a konkrét személyek, cégek és gépjárművek szabálytalanságáról szól,</li>
                                        <li>hajléktalan emberekről szól,</li>
                                        <li>vagy az oldalunk által jelenleg nem kezelt településről érkezett.</li>
                                    </ul>
                                    Az ilyen bejelentéseket a myProjectn nem tesszük közzé.
                                    Köszönjük, hogy bejelentetted a problémát! Ha kérdésed van, fordulj hozzánk nyugodtan a
                                    <a href="mailto:kerdes@myproject.hu">kerdes@myproject.hu</a> címen. Megértésedet köszönjük!',
    'content.status.info.get_user_response' => 'Az ügyed megoldására kitűzött határidő lejárt, kérjük, jelezd nekünk hozzászólásban, hogy valóban megtette-e az illetékes a szükséges intézkedéseket.',
    'content.status.info.open' => 'Köszönjük a{reportLabel}! Az ügy adatlapját itt éred el:',
    'content.status.info.resolve' => 'A{reportLabel} megoldódott.',
    'content.status.info.response' => '{institutionName} válasza megérkezett a{reportLabel}re:',
    'content.status.info.send_to_authority' => 'Minden szükséges információ rendelkezésre áll, a{reportLabel} csapatunk továbbította ennek az illetékesnek: {institutionName}{content}',
    'content.status.info.waiting_for_info' => 'Még nem kaptunk elegendő információt ahhoz, hogy továbbítani tudjuk az ügyet az illetékesnek. Az oldalon hozzászólásban vagy emailben a <a href="mailto:kerdes@myproject.hu">kerdes@myproject.hu</a> címre küldött üzenetben pontosítsd a bejelentésed leírását és ellenőrizd a probléma pontos címét. Mindenképpen csatolj még olyan kép(ek)et, amin a probléma környezete is könnyen beazonosítható, hogy ezzel is segítsük az illetékesek gyors és hatékony munkavégzését. Arról hogy miért fontos, hogy további fotókat küldj, <a href="http://bit.ly/katyumakro">itt olvashatsz bővebben</a>. <br> Figyelj arra, hogy ha 30 napon belül nem érkezik visszajelzés tőled, akkor a bejelentésedet töröljük.',
    'content.status.info.waiting_for_response' => 'Az ügyed megoldásra vár, jelezd nekünk, hogy valóban megtette-e az illetékes a szükséges intézkedéseket.',
    'content.status.info.waiting_for_solution' => 'A{reportLabel}re válaszolt az illetékes, most a megoldásra várunk. A későbbiek során értesíteni fogunk még téged a fejleményekről. Köszönjük, hogy segítettél szebbé tenni városod!',
    'institution.resolve_report.body' => 'Az alábbi bejelentés megoldásának sikerességét visszaigazolták!',
    'institution.resolve_report.header' => 'Tisztelt {institution_name}!',
    'institution.send_report.body' => 'Az alábbi lakossági bejelentést kaptuk, ami az Önök hatáskörébe tartozik:<br /><br />Név: <a href="{link}">{report_name}</a><br />Kategória: {category}<br />Leírás: {description}<br />Lokáció: {user_location}<br /><br />Kérjük, hogy erre a levélre válaszoljanak, hogy rendszerünk fel tudja azt dolgozni.',
    'content.status.info.send_to_authority.partner' => '<br><br> A II. kerületi bejelentések gondozását Budapest Főváros II. Kerületi Önkormányzata támogatja.',
    'subject.answer' => 'Válasz érkezett',
    'subject.incoming_email' => 'Válasz érkezett',
    'subject.close' => 'Bejelentés lezárva',
    'subject.delete' => 'Törölt bejelentés',
    'subject.delete_report' => 'A bejelentésed töröltük',
    'subject.get_user_response' => 'Ez az ügy a visszajelzésedre vár',
    'subject.info_request' => 'Bejelentés adatainak kiegészítése',
    'subject.new_report_acknowledgement' => 'Bejelentés visszaigazolása',
    'subject.new_report_notification' => 'Új bejelentés érkezett',
    'subject.open' => 'Új bejelentés',
    'subject.resolve' => 'Megoldott ügy',
    'subject.response' => 'Válaszolt az illetékes!',
    'subject.response_request' => 'Megoldott ügy ellenőrzése',
    'subject.send_to_authority' => 'A bejelentést továbbítottuk az illetékesnek',
    'subject.sent_to_authority' => 'Az ügyet továbbítottuk',
    'subject.waiting_for_info' => 'Hiányzó információk',
    'subject.waiting_for_resolution' => 'Az ügyedre válaszolt az illetékes',
    'subject.waiting_for_response' => 'Az ügy visszajelzésre vár',
    'subject.waiting_for_solution' => 'Az ügy megoldása folyamatban',
    'contact.email' => 'Email cím',
    'contact.message' => 'Üzenet',
    'contact.name' => 'Feladó',
    'contact.subject' => 'Üzenet érkezett a Kapcsolat oldalról',
    'contact.title' => 'Az alábbi levél érkezett a {name} oldalról:',
    'content.label.report.own' => ' bejelentésed',
    'content.label.report.watched' => 'z általad követett bejelentés',
    'content.new-report-comment-followed' => '{fullName} hozzászólt az alábbi bejelentéshez:',
    'content.new-report-comment-owned' => '{fullName} hozzászólt a bejelentésedhez:',
    'content.digest.changed-status' => 'A(z) {reportLink} bejelentés <em>{newStatus}</em> státuszba került.',
    'content.digest.new-report-comment-followed' => '{fullName} hozzászólt a(z) {reportLink} bejelentéshez.',
    'content.digest.new-report-comment-owned' => '{fullName} hozzászólt a(z) {reportLink} bejelentésedhez.',
    'content.digest.response' => '{institutionName} válasza megérkezett a(z) {reportLink} bejelentésedre:',
    'footer.too_many_emails' => 'Sok emailt kapsz tőlünk? Módosítsd az ',
    'footer.too_many_emails_link_to_profile' => 'Értesítések beállításait',
    'hello' => 'Szia,',
    'hello_with_name' => 'Szia {name}!',
    'institution.send_report.header' => 'Tisztelt {name} ({institution_name})!',
    'password-recovery.body' => 'Nemrég jelezted a myProjectn, hogy elfelejtetted a jelszavad  és szeretnél egy újat. Kattints az alábbi gombra, és add meg új jelszavad:',
    'password-recovery.body_end' => 'Ha esetleg mégsem te kérted, akkor nyugodtan hagyd figyelmen kívül ezt az emailt. A fent található link a mai nap végéig él.',
    'password-recovery.link' => 'Megadom az új jelszavam',
    'password-recovery.subject' => 'Jelszó módosítás',
    'signature' => 'Üdvözlettel,<br />myProject.hu csapata',
    'subject.daily-mail' => 'Ezek történtek a bejelentéseiddel - {date}',
    'subject.new-report-comment-followed' => '{fullName} hozzászólt egy bejelentéshez amit követsz',
    'subject.new-report-comment-owned' => '{fullName} hozzászólt egy bejelentésedhez',
    'subject.resend_report' => 'Újraküldés: Új bejelentés',
    'subject.send_report' => 'Új bejelentés',
    'subject.welcome_after_regform' => 'Üdvözlünk a myProjectnél, íme pár tanács a kezdéshez!',
    'subject.welcome_after_submit' => 'Üdvözlünk a myProjectnél, íme pár tanács a kezdéshez!',
    'daily_mail.new_activity' => 'Fejlemény történt az alábbi üggyel kapcsolatban <br>',
    'daily_mail.activities' => 'Az alábbi fejlemények történtek a bejelentéseiddel  <br> kapcsolatban',
    'daily_mail.own_reports' => 'Saját bejelentéseim',
    'daily_mail.followed_reports' => 'Követett bejelentéseim',
];
