<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'integrity-constraint-violation' => 'Ez a bejegyzés nem törölhető, mert tartoznak hozzá egyéb bejegyzések!',
    'first-line' => 'Sajnos a fenti hiba miatt nem tudjuk teljesíteni a kérést.',
    'invalid-password-recovery-token' => 'Hibás jelszómódosító link!',
    'no-user-found' => 'Nincs ilyen felhasználó a rendszerben!',
    'page-title' => '404<br>Az oldal nem található.',
    'second-line' => 'Kérjük próbáld újra, vagy vedd fel velünk a kapcsolatot.',
];
