<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'contact.create' => 'Kapcsolat hozzáadása',
    'contact.delete' => 'Kapcsolat törlése',
    'contact.delete.message' => 'Valóban törlöd a kapcsolatot az intézmény profiljából?',
    'create' => 'Intézmény hozzáadása',
    'delete' => 'Intézmény törlése',
    'delete.description' => 'Az intézmény profilja és a kapcsolatai törlődnek, de a kapcsolódó bejelentések továbbra is megmaradnak.',
    'delete.message' => 'Valóban törlöd az intézményt a rendszerből?',
    'index.all_cities' => 'Összes település',
    'index.reports' => 'Bejelentések',
    'index.pr_page.new' => 'Új pr oldal',
    'index.pr_page.update' => 'Pr oldal szerkesztése',
    'type.district' => 'Kerület',
    'type.other_institution' => 'Egyéb intézmény',
    'type.town_hall' => 'Városháza',
    'type.unknown' => 'Ismeretlen',
    'update.contacts' => 'Kapcsolatok',
];
