<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'comment.placeholder' => 'Szólj hozzá te is a bejelentéshez! Minden véleményre kiváncsiak vagyunk.',
    'footer.back_to_top' => 'Vissza az oldal tetejére',
    'footer.follow_us' => 'Kövess minket!',
    'footer.how_it_works' => 'Hogyan működik?',
    'footer.institution.0' => 'Mit tegyek, ha engem értesítettek egy bejelentésről?',
    'footer.institution.1' => 'Segítséget kérek!',
    'footer.join_us.0' => 'Szívesen részt vennél a myProject munkájában?',
    'footer.join_us.1' => 'Csatlakozz!',
    'footer.know_more' => 'Tudj meg többet a myProjectről!',
    'footer.know_more.annual_reports' => 'Beszámolók és közhasznúsági jelentések',
    'footer.know_more.how' => 'Hogyan működik?',
    'footer.know_more.mobile_app' => 'Mobil alkalmazás',
    'footer.know_more.statistics' => 'Statisztika',
    'footer.know_more.team' => 'A csapat',
    'footer.know_more.widget' => 'myProject widget',
    'footer.our_partners' => 'Partnereink',
    'footer.social.facebook' => 'Lájkolj minket Facebookon',
    'footer.social.instagram' => 'Kövess minket Instagrammon',
    'footer.social.twitter' => 'Csiripelj velünk Twitteren',
    'footer.social.blog' => 'Olvasd a blogunkat',
    'footer.social.rss' => 'Iratkozz fel RSS feedünkre',
    'footer.stat.resolved' => 'megoldott ügy',
    'footer.stat.title' => 'myProject számokban',
    'footer.stat.unresolved' => 'megoldásra váró ügy',
    'footer.stat.users' => 'elégedett felhasználó',
    'footer.support' => 'Támogasd',
    'footer.write_to_us' => 'Írj nekünk',
    'footer.write_to_us.0' => 'Lépj velünk kapcsolatba!',
    'footer.write_to_us.1' => 'Kérdésed van? Vagy csak szeretnéd jobban megismerni a myProject-t?',
    'generic.all' => 'Összes',
    'generic.all_city' => 'Összes település',
    'generic.all_districts' => 'az összes kerületben',
    'generic.all_institution' => 'Összes illetékes',
    'generic.all_my_reports' => 'Összes bejelentésed',
    'generic.all_reports' => 'Összes ügy',
    'generic.choose' => 'Válassz',
    'generic.close' => 'Bezárás',
    'generic.email' => 'E-mail cím',
    'generic.follow' => 'Kövesd',
    'generic.following' => 'Követem',
    'generic.login' => 'Bejelentkezés',
    'generic.navigation' => 'Navigáció',
    'generic.no' => 'Nem',
    'generic.password' => 'Jelszó',
    'generic.search' => 'Keresés',
    'generic.search_in_reports' => 'Keresés a bejelentések között',
    'generic.submit' => 'Küldés',
    'generic.toplist' => 'Ranglista',
    'generic.toplist.score' => '{score} pont',
    'generic.yes' => 'Igen',
    'new_admin' => 'Ügykezelő hozzáadása',
    'new_city' => 'Település hozzáadása',
    'report.generic_information' => 'Általános információk',
    'report.location' => 'Helyszín',
    'report.pictures' => 'Képek',
    'report.resolved_issue' => 'Már <strong class="filter__count">{number}</strong> megoldott bejelentés',
    'report.user' => 'Bejelentő',
    'update_city' => 'Település módosítása',
    'upload.failed' => 'Sikertelen feltöltés',
    'pr_page.create' => 'Új pr oldal létrehozása',
    'pr_page_news.create' => 'Új hír létrehozása',
];
