<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'report_list' => 'Bejelentések listája',
    'about' => 'Rólunk',
    'admin' => 'Ügykezelők',
    'apps' => 'Mobil app',
    'apps.blog' => 'Blog',
    'apps.disabled' => 'Mobil',
    'city' => 'Települések',
    'contact' => 'Kapcsolat',
    'cron-log' => 'Logok',
    'dropdown.lead' => 'Kíváncsi vagy a myProject.hu működésére? Segítünk megoldani a problémádat.',
    'dropdown.lead2' => 'Itt találod azokat az oldalainkat, ahol kiemelt témákban segíthetsz ügyeket gyűjteni a városból. 
    Azt is nézd meg, hogyan csatlakozhatsz a myProject csapatához, mindig keresünk önkénteseket!',
    'dropdown.title' => 'Hogyan működik?',
    'dropdown.title2' => 'Vegyél részt',
    'featured' => 'Kiemelt bejelentések',
    'featured_more' => 'Még több kiemelt bejelentés',
    'get_to_know_us' => 'Ismerj meg minket',
    'institution' => 'Intézmények',
    'pr_page' => 'Pr oldalak',
    'login' => 'Belépek',
    'login_to_view_profile' => 'Profilod megtekintéséhez lépj be',
    'logout' => 'Kijelentkezés',
    'more_reports' => 'További bejelentések',
    'new' => 'Friss bejelentések',
    'new_more' => 'Még több friss bejelentés',
    'new_report' => 'Probléma bejelentése',
    'map-layer' => 'Térképrétegek',
    'money-donation' => 'Pénz adományok',
    'partners' => 'Partnerek és támogatók',
    'password' => 'Jelszó módosítás',
    'profile' => 'Profilom',
    'register' => 'Regisztrálok',
    'report' => 'Bejelentések',
    'score' => '{score} pont',
    'search.all_results' => 'Összes találat',
    'search.no_results' => 'Nincs találat.',
    'search.placeholder' => 'Bejelentés keresése',
    'statistics' => 'Statisztika',
    'support' => 'Támogass',
    'task' => 'Feladatok',
    'team' => 'A csapat',
    'tos' => 'Adatkezelési tájékoztató',
    'user' => 'Felhasználók',
    'volunteer' => 'Csatlakozz',
    'participate' => 'Vegyél részt',
    'pr_page_news' => 'Hírek',
];
