<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'title.base' => 'myProject.hu',
    'author.content' => 'myProject szervezet',
    'description.default' => 'myproject.hu. Ha megosztod, megoldod.',
    'og.site_name' => 'www.myproject.hu',
    'title.about' => 'Rólunk',
    'title.annual_reports' => 'Beszámolók és közhasznúsági jelentések',
    'title.api' => 'API Documentation',
    'title.apps' => 'Mobil alkalmazás',
    'title.bureau' => 'Levelet kapott tőlünk? Így válaszoljon!',
    'title.contact' => 'Kapcsolat',
    'title.default' => 'myProject.hu. Ha megosztod, megoldod.',
    'title.howitworks' => 'Hogyan működik',
    'title.partners' => 'Partnerek és támogatók',
    'title.rss' => 'RSS',
    'title.statistics.city' => 'Települések statisztikája',
    'title.statistics.index' => 'Statisztika',
    'title.statistics.institution' => 'Illetékesek statisztikája',
    'title.statistics.user' => 'Felhasználók statisztikája',
    'title.support' => 'Támogasd',
    'title.team' => 'A csapat',
    'title.tos' => 'Adatkezelési tájékoztató',
    'title.volunteer' => 'Jelentkezz önkéntesnek!',
];
