<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'pr_page' => 'Pr oldal',
    'update.title' => 'Cím',
    'update.introduction' => 'Bemutatkozó tartalom',
    'update.info.web_page' => 'Weboldal',
    'update.info.email' => 'E-mail',
    'update.info.phone' => 'Telefon',
    'update.info.address' => 'Cím',
    'update.map_status' => 'Térkép státusz',
    'update.custom_color' => 'Kiemelt szín színkódja (pl.: #81bb41)',
    'update.status' => 'Az oldal státusza',
    'update.social_feed_url' => 'Megjelenítendő közösségi felület url-je (facebook, twitter, instagram)',
    'update.video_url' => 'Youtube videó url-je',
    'update.cover_file_name' => 'Borítókép',
    'update.logo_file_name' => 'Logó',
    'update.url' => 'Az oldal url címe',
    'update.title.introduction' => 'Bemutatkozás',
    'update.title.connection' => 'Kapcsolat',
    'update.title.appearance' => 'Megjelenés és pr elemek',
    'update.title.map' => 'Térkép',
    'update.title.settings' => 'Általános beállítások, adatok',
    'map_status.all' => 'Összes',
    'map_status.in_progress' => 'Folyamatban lévő',
    'map_status.resolved' => 'Megoldott',
    'info.web_page' => 'Weboldal: ',
    'info.email' => 'E-mail: ',
    'info.phone' => 'Telefon: ',
    'info.address' => 'Cím: ',
    'statistic.resolved_reports' => 'Megoldott bejelentések',
    'statistic.response_time' => 'Válaszadási idő',
    'statistic.response_time.day' => ' nap',
    'statistic.resolved_users_reports' => 'Megoldott saját bejelentéseid',
    'statistic.in_progress_reports' => 'Folyamatban lévő ügyek',
    'map.title.0' => 'Összes ügy',
    'map.title.1' => 'Folyamatban lévő ügyek',
    'map.title.2' => 'Megoldott ügyek',
    'button.news' => 'Hírek szerkesztése',
    'button.upload_image' => 'Új kép feltöltése',
    'button.send_report' => 'Probléma bejelentése a szervezetnek',
    'title.news' => 'Hírek',
    'confirm.delete.title' => 'Pr oldal törlése',
    'confirm.delete.confirm' => 'Valóban törlöd a pr oldalt a rendszerből?',
    'confirm.delete.message' => 'A pr oldal adatai és a hozzá tartozó hírek törlődnek.',
    'status.public' => 'Nyilvános',
    'status.not_public' => 'Nem nyilvános',
    'grid.status' => 'Az oldal státusza',
    'grid.created_at' => 'Létrehozva',
    'tooltip.resolved_reports' => 'Jelenleg a szervezetnek ennyi bejelentését tartjuk számon megoldottként a myProject-n.',
    'tooltip.response_time' => 'A válaszadási időt az olyan bejelentések válaszadási idejének átlaga adja ki, melyekre ez a szervezet már válaszolt és nem volt más illetékes érintett az ügy megoldásában.',
    'tooltip.resolved_users_reports' => 'Ennyi bejelentést küldtél te, amit ennek az illetékesnek küldtünk ki.',
    'tooltip.in_progress_reports' => 'Ennyi bejelentése van a szervezetnek, amelyet már megkapott intézkedésre, de még nem zártuk le megoldott vagy megoldatlan státusszal.',
];