<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'news' => ' pr oldal hírei',
    'status.active' => 'Aktív',
    'status.inactive' => 'Inaktív',
    'update.title' => 'Cím',
    'update.text' => 'Szöveg',
    'update.highlighted' => 'Kiemelt',
    'update.published_at' => 'Publikálás dátuma',
    'update.image_file_name' => 'Kép',
    'create' => 'Új hír létrehozása',
    'button.upload_image' => 'Új kép feltöltése',
    'highlighted' => 'Kiemelt hír',
    'button.activate' => 'Aktiválás',
    'button.inactivate' => 'Inaktiválás',
    'button.save_changes' => 'Változtatások mentése',
    'button.highlight' => 'Kiemelt státusz hozzáadása',
    'button.undo_highlight' => 'Kiemelt státusz visszavonása',
    'button.more' => 'Tovább',
    'confirm.highlight.title' => 'Kiemelt státusz szerkesztése',
    'confirm.highlight.confirm.first_part' => 'Valóban a(z) ' ,
    'confirm.highlight.confirm.second_part' => ' legyen az új kiemelt hír?',
    'confirm.undo_highlight.confirm.first_part' => 'Valóban törlöd a(z) ',
    'confirm.undo_highlight.confirm.second_part' => ' hír kiemelt státuszát?',
    'confirm.highlight.message.first_part' => 'Már van egy kiemelt hír (',
    'confirm.highlight.message.second_part' => '), ami el fogja veszteni a kiemelt státuszát.',
    'confirm.delete.title' => 'Hír törlése',
    'confirm.delete.confirm.first_part' => 'Valóban törlöd a(z) ',
    'confirm.delete.confirm.second_part' => ' hírt?',
];