<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'my_reports' => 'bejelentésem',
    'no_city_district_set' => 'Nem állított be várost',
    'report.set_as_city' => 'Beállítom városomnak',
    'reports' => 'bejelentés',
    'to_back' => 'Vissza az előző oldalra',
    'to_frontpage' => 'Vissza a főoldalra',
    'city_district_filtered_reports' => 'Az itt beállított településen (és ha van, kerületben) található bejelentéseket fogjuk neked megjeleníteni.',
    'menu.drafts' => 'Piszkozataim ({count})',
    'menu.logout' => 'Kilépés',
    'menu.manage' => 'Profilom módosítása',
    'menu.my_reports' => 'Bejelentéseim ({count})',
    'modify_password' => 'Jelszó módosítása',
    'modify_profile' => 'Profil módosítása',
    'notifications' => 'Értesítők',
    'old_password_alert' => 'A jelenlegi jelszavad nem biztonságos, kérlek változtasd meg!',
    'password_must_be' => 'A jelszó az alábbi szabályoknak feleljen meg:',
    'personal_information' => 'Személyes információk',
    'profile-picture' => 'Profilképem',
    'profile-picture-updated' => 'Sikeresen módosítottad a profilképed',
    'report.count' => 'bejelentés',
    'report.inprogress' => 'folyamatban',
    'report.solved' => 'megoldott',
    'report.unsolved' => 'megoldatlan',
    'save_changes' => 'Mentem a módosításokat',
    'send_frequency' => 'ILYEN GYAKORISÁGGAL',
    'send_notification' => 'EZEKRŐL KÉREK ÉRTESÍTŐT',
    'set_as_password' => 'Beállítom jelszónak',
    'title' => 'Profilom',
    'title.drafts' => 'Piszkozataim',
    'top.setCity' => 'Állítsd be a településed',
    'view_title' => '{name} profilja',
    'your_password_must_be' => 'Jelszavad legyen:',
];
