<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'update' => 'Szabály szerkesztése',
    'create' => 'Szabály hozzáadása',
    'delete' => 'Szabály törlése',
    'delete.message' => 'Valóban törlöd a szabályt a település profiljából?',
    'grid.institution' => 'Illetékes',
    'grid.street_group' => 'Utcacsoport',
    'placeholder.category' => 'Válassz kategóriát, ha szükséges',
    'placeholder.district' => 'Válassz kerületet, ha szükséges',
    'placeholder.institution' => 'Válassz illetékest',
    'placeholder.street' => 'Válassz utcát, ha szükséges',
    'status.active' => 'Aktív',
    'status.inactive' => 'Inaktív',
    'status.not_public' => 'Nem nyilvános',
    'status.public' => 'Nyilvános',
    'update.email_addresses' => 'E-mail címek',
    'update.note' => 'Megjegyzés:',
];
