<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'label.institution' => '',
    'toplist.name' => 'Név',
    'toplist.rank' => 'Helyezés',
    'about' => 'Kiváncsi vagy, hogy hány bejelentés született eddig településeden? Mik a leggyakoribb problémák? Melyik illetékes oldotta meg a legtöbb problémát?',
    'label.city' => 'City',
    'label.days' => 'days',
    'label.limit' => 'limit',
    'title' => 'myProject számokban',
    'toplist.global_toplist' => 'Összesített toplista',
    'toplist.how_it_works' => 'Hogyan működik a toplista?',
    'toplist.monthly_toplist' => 'Havi toplista',
    'toplist.points' => 'pont',
];
