<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'streetgroup.update' => 'Utcacsoport szerkesztése',
    'update' => 'Utca szerkesztése',
    'create' => 'Utca hozzáadása',
    'delete' => 'Utca törlése',
    'delete.message' => 'Valóban törlöd az utcát a település profiljából?',
    'grid.district' => 'Kerület',
    'search' => 'Keresés',
    'search.all_districts' => 'Összes kerület',
    'search.district' => 'Kerület',
    'search.name' => 'Név',
    'streetgroup.create' => 'Utcacsoport hozzáadása',
    'streetgroup.delete' => 'Utcacsoport törlése',
    'streetgroup.delete.message' => 'Valóban törlöd az utcacsoportot a település profiljából?',
    'streetgroup.search.name' => 'Keresés',
];
