<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'activity.answer' => '{institution} válasza megérkezett.',
    'activity.comment' => '{user} hozzászólt a következő bejelentéshez: {report}',
    'activity.new_info' => '{user} további információt küldött.',
    'activity.no_answer' => '{institution} nem válaszolt {days} napon belül.',
    'activity.no_new_info' => '{user} nem küldött további információt {days} napon belül.',
    'activity.no_response' => '{user} nem küldött visszajelzést {days} napon belül.',
    'activity.response' => '{user} visszajelzést küldött.',
    'activity.incoming_email' => '{institution} emailt küldött.',
    'activity.incoming_email_plain' => '{email} e-mail címről válasz érkezett.',
    'assign.description' => 'A <b>{from}</b> választ küldött egy ügyhöz, amit nem a kapcsolt email címre küldött, hanem a <b>{to}</b> címre. Ezért a választ először egy már meglévő ügyhöz kell kapcsolni.',
    'assign.mail.attachment' => 'Csatolmány',
    'assign.mail.content' => 'Levél tartalma',
    'assign.mail.subject' => 'Levél tárgya',
    'assign.placeholder' => 'Ügy keresése...',
    'assign.title' => 'Válasz hozzárendelése',
    'index.activity' => 'Aktivitás',
    'index.assign' => 'Ügy hozzákapcsolása',
    'index.report' => 'Kapcsolódó ügy',
    'no-report-to-assign' => 'Nincs (számodra) elérhető olyan bejelentés amihez hozzá lehetne kötni ezt a választ!',
    'no-task-found' => 'jelenleg nincs feladat.',
    'tab.active' => 'Új aktivitások',
    'tab.comment' => 'Új hozzászólások',
    'tab.new' => 'Új bejelentések',
];
