<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'update.success' => 'Sikeresen módosítva.',
    'confirm' => 'Kattints a linkre, hogy aktiváld magad {link}',
    'delete' => 'Felhasználó törlése',
    'delete.description' => 'A felhasználó profilja nem lesz elérhető, de eddigi bejelentései továbbra is megmaradnak.',
    'delete.message' => 'Valóban törlöd a felhasználót a rendszerből?',
    'email-not-unique' => '<p>A megadott e-mail cím már regisztrálva van a rendszerben.</>
                        <ul class="tooltip__list">
                            <li><a class="link link--info" href="{urlLogin}">Lépj be!</a> fiókodba vagy</li>
                            <li><a class="link link--info" href="{urlRecover}">Kérj új jelszót</a>, ha elfelejtetted.</li>
                        </ul>',
    'form.email' => 'E-mail cím',
    'form.first_name' => 'Keresztnév',
    'form.last_name' => 'Vezetéknév',
    'form.new_password' => 'Új jelszó',
    'form.old_password' => 'Jelenlegi jelszó',
    'form.password' => 'Jelszó',
    'form.password_repeat' => 'Jelszó újra',
    'form.phone_number' => 'Telefonszám',
    'form.repeat_password' => 'Jelszó mégegyszer',
    'index.full_name' => 'Név',
    'index.reports' => 'Bejelentések',
    'notification.0' => 'Nincs értesítés.',
    'notification.1' => 'Azonnal',
    'notification.1.hint' => 'Amint történik aktivitás a bejelentésben, egyből értesítünk.',
    'notification.2' => 'Napi összefoglaló',
    'notification.2.hint' => 'A nap elején küldünk egy összefoglalót az azt megelőző nap aktivitásairól.',
    'notificationtype.1' => 'Saját bejelentések',
    'notificationtype.1.hint' => 'Bejelentések, amiket te küldtél be',
    'notificationtype.2' => 'Követett bejelentések',
    'notificationtype.2.hint' => 'Bejelentések, amiket követsz',
    'report.created_at' => 'Létrehozva',
    'report.institution_name' => 'Illetékes neve',
    'report.latitude' => 'Szélességi kör',
    'report.longitude' => 'Hosszúsági fok',
    'report.new_report' => 'új bejelentés',
    'report.report_category_name' => 'Kategória',
    'report.resolved' => 'megoldott',
    'report.status' => 'Állapot',
    'report.unresolved' => 'megoldatlan',
    'report.url' => 'Hivatkozás',
    'report.user_location' => 'Cím',
    'report.waiting_for_info' => 'kiegészítésre vár',
    'report.waiting_for_answer' => 'válaszra vár',
    'report.waiting_for_response' => 'visszajelzésre vár',
    'report.waiting_for_solution' => 'megoldásra vár',
    'status.active' => 'Aktív',
    'status.inactive' => 'Inaktív',
    'update.api' => 'API',
    'update.password_change' => 'Jelszó módosítás',
    'update.personal_info' => 'Személyes adatok',
    'update.report' => 'bejelentés',
    'update.reports' => 'Bejelentések',
    'update.upload' => 'Új kép feltöltése',
    'kill.message' => 'A felhasználó összes bejelentése, hozzászólása, bejelentés aktivitása, értékelése és adata végérvényesen törlődik. BIZTOSAN AKAROD???',
];
