<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'annual_reports.column1.title' => 'Reports',
    'annual_reports.column2.title' => 'Documents',
    'annual_reports.column3.title' => 'Sponsors',
    'about.lead' => 'Find out more about our project here',
    'about.title' => 'About us',
    'annual_reports.lead' => 'This page contains our annual reports and documents.',
    'annual_reports.title' => 'Financial reports and annual reports',
    'contact.content' => 'Do you have a question? Do not hesitate to ask.',
    'contact.success_message' => 'Thank you for sharing your thoughts with us.',
    'contact.title' => 'Contact us',
    'howitworks.lead' => 'Take the first step to resolve street-fixing problems in your neighbourhood. Upload them to myProject, and we will sort out the rest.',
    'howitworks.title' => 'How does it work?',
    'partners.lead' => 'Our main supporters.',
    'partners.title' => 'Our partners and sponsors',
    'section.annual_reports.lead' => 'Check out our annual report and other legal documents here.',
    'section.annual_reports.link' => 'Chech out the reports',
    'section.howitworks.lead' => 'Take the first step to resolve street-fixing problems in your neighbourhood. Upload them to myProject, and we will sort out the rest.',
    'section.partners.lead' => 'These are our main supporters.',
    'section.partners.link' => 'See who they are',
    'section.statistics.lead' => 'See how many reports were sent from your neighbourhood. What are the most common problems?',
    'section.statistics.link' => 'Check out our stats',
    'section.tos.lead' => 'In order to use our site please read our Terms of Service.',
    'section.tos.link' => 'Read the terms',
    'team.lead1' => 'Our volunteers help you find the institutions who should address the problem.',
    'team.lead2' => 'We are always looking for volunteers.',
    'team.title' => 'Meet the team',
];
