<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'this-model-does-not-exists-or-you-dont-have-permission' => 'Or you do not have permission to perform this action or item you requested does not exist.',
    'you-dont-have-permission-to-this-page' => 'You do not have permission to perform this action.',
    'activity.answer_request' => 'Request response',
    'activity.new_report' => 'Manage new report',
    'activity.resolve' => 'Close report',
    'activity.response_request' => 'Feedback request',
    'create' => 'Add administrator',
    'delete' => 'Delete administrator',
    'delete.message' => 'Are you sure you want to delete the admin from the system?',
    'grid.summary' => '<div class="summary pull-right"> All <b>{totalCount, number}</b> hit on <b>{pageCount, number}</b> pages  </div>',
    'index.full_name' => 'Name',
    'index.score' => 'Points',
    'status.active' => 'Active',
    'status.inactive' => 'Inactive',
    'status.super_admin' => 'Super Admin',
    'update.password_change' => 'Change password',
    'update.activity' => 'Activity',
    'update.activity_help' => 'What are activity points?',
    'update.activity_help_1' => 'Activity points are given to admins after managing reports, or giving feedback on them.',
    'update.activity_help_2' => 'Each activity in the admin gives you one point.',
    'update.activity_help_3' => 'Since it may occur that the many people are working on the same report, all activities are rewarded the same.',
    'update.activity_score' => 'Activity points',
    'update.city' => 'City',
    'update.pr_page' => 'Pr page',
    'update.edit_permission' => 'Edit Permission',
    'update.permission' => ' Permission ',
    'update.personal_info' => ' Personal data ',
    'update.rank' => ' You are (z) {rank}. in report management ',
    'update.score' => 'points',
    'update.success' => 'Successfully modified.',
    'update.system_info' => 'System Information',
    'update.upload' => 'Upload pictures',
    'hotkeys.title' => ' Shortcuts',
    'hotkeys.general' => 'Works everywhere',
    'hotkeys.general.help' => 'Show Help',
    'hotkeys.report.view' => 'View the report page',
    'hotkeys.report.view.edit' => ' Edit ',
    'hotkeys.report.view.open' => 'Open public report page',
    'hotkeys.report.view.send' => 'Send it to authority',
    'hotkeys.report.view.upload' => 'Upload reply',
    'hotkeys.report.view.delete' => 'Delete',
    'hotkeys.report.view.changestatus' => 'Change Status',
    'hotkeys.report.update' => 'View edit report page',
    'hotkeys.report.update.compare' => 'Compare it with the original',
    'label.reports' => 'Reports',
    'label.link_to_report' => 'Link to report',
    'label.comments_count' => '# of comments',
];

