<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Recent headlines' => '',
    'appbox.content1.disabled' => '',
    'successful_report_status_change' => '',
    'about.howitworks.lead' => '@@@@',
    'about.howitworks.title' => '@@@@',
    'about.lead' => '@@@@',
    'about.title' => '@@@@',
    'appbox.content' => '@@@@',
    'footer.cookie.dismiss' => 'OK',
    'appbox.appstore' => 'Download from the App Store',
    'appbox.content1' => 'Download our free mobile application!',
    'appbox.content2' => 'Follow the status of your report on your smartphone.',
    'appbox.googleplay' => 'Get it from Google Play',
    'appbox.title' => 'Our app on your mobile',
    'error_in_form_submit' => 'There is a problem with some of the entries.',
    'footer.cookie.learn_more' => 'I would like to know more.',
    'footer.cookie.message' => 'We use cookies and similar technologies.',
    'hero-bottom-dual.support.lead' => 'Support our work with a monthly donation.<br><br>Our tax number for 1% personal income tax assignments: TAX NUMBER',
    'hero-bottom-dual.support.title' => 'Support myProject',
    'hero.know_more' => 'Learn more about our work',
    'hero.lead' => 'Our team helps citizens to make cities better by mapping street-fixing issues such as potholes, missing pedestrian crossings, or damaged street furniture. Upload your photo and description, and we will sort out the rest.',
    'hero.report_problem' => 'Report a problem',
    'hero.support' => 'Donate',
    'hero.title' => 'Let us know what needs to be fixed',
    'login.form.rememberMe' => 'Remember me',
    'nothing_selected' => 'Not set',
    'pagination.link.next' => 'Next',
    'pagination.link.prev' => 'Previous',
    'pagination.link.last' => 'Last',
    'pagination.link.first' => 'First',
    'password.old_password_incorrect' => 'The current password is incorrect',
    'successful_password_update' => 'You have changed your password',
    'successful_profile_update' => 'You have successfully changed your profile',
];
