<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'log-in-with-' => '',
    'social-profile-joined-to-account' => '',
    'successful-registration' => '',
    'log-in-with-facebook' => 'with your Facebook account',
    'log-in-with-google' => 'with your Google account',
    'already-registered?' => 'Already have an account?',
    'flash.new-password-successfully-set' => 'Password successfully set',
    'forgot-password-question' => 'Forgot your password?',
    'login-legend' => 'Login',
    'no-accout-yet?' => 'If you are not registered yet',
    'or' => 'Or',
    'password-recovery-legend' => 'Forgot your password?',
    'password-recovery-paragraph' => 'No problem, enter your email address and we\'ll send you a link to change your password.',
    'password-recovery-success-legend' => 'Check your email',
    'password-recovery-success-paragraph' => 'In a few seconds an email will be sent to your address with a link to change your account password. ',
    'password-requirements-capital' => 'It should contain a capital letter.',
    'password-requirements-label' => 'The password should be ',
    'password-requirements-length' => 'At least six characters long',
    'password-requirements-number' => 'It should contain a number',
    'register-legend' => 'Registration',
    'remember-your-password-question' => 'Do you remember your password?',
    'set-new-password.legend' => 'Change your password please',
    'wrong-username-or-password' => 'Incorrect username or password.',
];
