<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'require-new-password' => 'Request new password',
    'show_on_map' => 'Show on map',
    'add' => 'Add',
    'anonymous_report' => 'I want to stay anonymous',
    'api.generate' => 'Generate key',
    'api.reset' => 'Regenerate key',
    'api.revoke' => 'Revoke',
    'assign' => 'Assign',
    'back-to-home' => 'Back to main page',
    'cancel' => 'Cancel',
    'delete' => 'Delete',
    'draft_report' => 'Save it as draft',
    'erase-search-filters' => 'Clear search',
    'i-would-like-new-password' => 'I want a new password',
    'log-in' => 'Log me in',
    'login' => 'Login',
    'login2' => 'Log in',
    'next' => 'Next',
    'register' => 'Registration',
    'register!' => 'Sign up',
    'retry' => 'Try again',
    'save' => 'Save',
    'save_report' => 'Submit report',
    'send' => 'Submit',
    'send2' => 'Send',
    'set-new-password' => 'I set a new password ',
    'submit' => 'Sending',
    'submit_contact' => 'Send message',
    'update' => 'Update',
    'upload' => 'Browse',
    'KILL' => 'KILL',
];
