<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'email account authentication failed' => '',
    'email_address-hint' => '',
    'mailServer config not exists' => '',
    'name_filter.hint' => '',
    'update.districts_tooltip' => 'It can be set to NO only when all districts are deleted.',
    'update.values' => 'Details',
    'create' => 'Add City',
    'grid.adminCount' => 'Manage admins',
    'grid.districtCount' => 'Districts',
    'grid.reportCount' => 'Reports',
    'grid.streetCount' => 'Streets',
    'search.all_statuses' => 'All statuses',
    'search.name' => 'Name',
    'search.status' => 'Status',
    'status.active' => 'Active',
    'status.inactive' => 'Inactive',
    'update' => 'Update city',
    'update.no_districts' => 'This city can not have districts.',
    'update.tab.districts' => 'Districts',
    'update.tab.rules' => 'Rules',
    'update.tab.streetgroups' => 'Street groups',
    'update.tab.streets' => 'Streets',
];
