<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'report.' => '',
    'report.class.' => '',
    'report.status.' => '',
    'report.class.0' => 'new',
    'report.class.1' => 'editing',
    'report.class.2' => 'waiting-for-info',
    'report.class.3' => 'waiting-for-answer',
    'report.class.4' => 'waiting-for-response',
    'report.class.5' => 'resolved',
    'report.class.6' => 'unresolved',
    'report.class.7' => 'deleted',
    'report.class.8' => 'waiting-for-solution',
    'report.class.9' => 'draft',
    'rule.category.' => '@@@@',
    'admin.permission.add' => 'Add',
    'admin.permission.admin' => 'Admins',
    'admin.permission.city' => 'Cities',
    'admin.permission.delete' => 'Delete',
    'admin.permission.kill' => 'Delete permanently',
    'admin.permission.edit' => 'Edit',
    'admin.permission.institution' => 'Institutions',
    'admin.permission.report' => 'Reports',
    'admin.permission.pr_page' => 'Pr pages',
    'admin.permission.statistics' => 'Statistics',
    'admin.permission.user' => 'Users',
    'admin.permission.view' => 'View',
    'loader-message' => 'Loading...',
    'no-information' => 'N/A',
    'report.filter.followed' => 'Followed',
    'report.filter.fresh' => 'New',
    'report.filter.nearby' => 'Near me',
    'report.filter.popular' => 'Popular',
    'report.filter.status.3' => 'Waiting for reply',
    'report.filter.status.4' => 'Waiting for confirmation',
    'report.filter.status.8' => 'Solution underway',
    'report.status.0' => 'New',
    'report.status.1' => 'Under review',
    'report.status.2' => 'Needs more info',
    'report.status.3' => 'Waiting for reply',
    'report.status.4' => 'Waiting for confirmation',
    'report.status.5' => 'Resolved',
    'report.status.6' => 'Unresolved',
    'report.status.7' => 'Deleted',
    'report.status.8' => 'Solution underway',
    'report.status.9' => 'Draft',
];
