<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'content.label.report.own' => '',
    'content.label.report.watched' => '',
    'content.new-report-comment-followed' => '',
    'content.new-report-comment-owned' => '',
    'content.status.info.' => '',
    'password-recovery.body_end' => '',
    'subject.' => '',
    'subject.new-report-comment-followed' => '',
    'subject.new-report-comment-owned' => '',
    'subject.resend_report' => '',
    'admin.new_report.header' => 'New report arrived',
    'content.status.info.delete' => 'Sorry but your report was deleted because we couldn\\t process it. Thanks for reaching out. ',
    'content.status.info.open' => 'Thank you for submitting the report, check out its page here: ',
    'content.status.info.resolve' => 'Your report{reportLabel} is solved:',
    'content.status.info.response' => '{institutionName} has sent a reply to your report: ',
    'content.status.info.send_to_authority' => 'Based on the information you sent us we notified {institutionName}.',
    'content.status.info.waiting_for_response' => 'Sorry but we need more information (a new photo or a more detailed description of location) to be able to send it to the relevant institution. ',
    'content.status.info.waiting_for_solution' => 'The official reply has arrived, now we are waiting for the works to be finished. We will keep you updated. ',
    'institution.resolve_report.body' => 'This report was confirmed as solved!',
    'institution.resolve_report.header' => 'Dear {institution_name},',
    'institution.send_report.body' => ' We received the following report addressed to you:<br /><br /> Subject: <a href="{link}">{report_name}</a><br /> Category: {category}<br /> Description: {description}<br /> Location: {user_location}<br /><br /> please respond to this email directly so our system can process it. ',
    'subject.delete' => 'Deleted report',
    'subject.delete_report' => 'Your report was deleted.',
    'subject.info_request' => 'Please provide more information',
    'subject.new_report_acknowledgement' => 'Your report has been accepted',
    'subject.new_report_notification' => 'Notification: new report',
    'subject.open' => 'New report',
    'subject.resolve' => 'Report Solved',
    'subject.response' => 'The lawyer responded to the competent',
    'subject.response_request' => 'Confirm that the report was Solved',
    'subject.send_to_authority' => 'The report has been sent to an authority',
    'subject.sent_to_authority' => 'The report has been sent to an authority',
    'subject.waiting_for_resolution' => 'The work to fix your report is in progress',
    'subject.waiting_for_response' => 'Missing information',
    'subject.waiting_for_solution' => 'The fixing work has started',
    'user.delete_report.body' => '@@@@',
    'user.delete_report.header' => '@@@@',
    'contact.email' => 'Email address',
    'contact.message' => 'Message',
    'contact.name' => 'Sender',
    'contact.subject' => 'Message from the site',
    'contact.title' => 'The following email was sent through {name} site',
    'footer.too_many_emails' => 'Are you getting too many emails? Change your ',
    'footer.too_many_emails_link_to_profile' => 'notification settings',
    'hello' => 'Hello,',
    'hello_with_name' => 'Hey {name},',
    'institution.send_report.header' => 'Dear {name} ({institution_name}),',
    'password-recovery.body' => ' Click on the link below to setup a new password ',
    'password-recovery.link' => 'To set a new password',
    'password-recovery.subject' => 'Change password',
    'signature' => 'All the best,<br />Our team',
    'subject.daily-mail' => 'Daily report history: {date}',
    'subject.send_report' => 'New report',
    'subject.welcome_after_regform' => 'Welcome to our community, here is how you can get started.',
    'subject.welcome_after_submit' => 'Welcome to our community, here is how you can get started.',
];
