<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'contact.create' => 'Add Contact',
    'contact.delete' => 'Delete Contact',
    'contact.delete.message' => 'Are you sure you want to delete the insitution contacts?',
    'create' => 'Add Institution',
    'delete' => 'Delete Institution',
    'delete.description' => 'The profile of the institution and the contacts are deleted, but the associated reports still exist.',
    'delete.message' => 'Are you sure you want to delete the insitution from the database?',
    'index.all_cities' => 'All cities',
    'index.reports' => 'Reports',
    'index.pr_page.new' => 'Add pr page',
    'index.pr_page.update' => 'Edit pr page',
    'type.district' => 'District',
    'type.other_institution' => 'Other institutions',
    'type.town_hall' => 'Town Hall',
    'type.unknown' => 'Unknown',
    'update.contacts' => 'Contacts',
];

