<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'footer.institution.0' => 'Do you work at a local authority and received an email from us?',
    'footer.institution.1' => 'Get in touch here',
    'footer.social.blog' => 'Our blog in Hungarian',
    'footer.social.facebook' => 'Follow us on Facebook',
    'footer.social.instagram' => 'Check out our Instagram',
    'footer.social.rss' => 'Subscribe to our RSS feed',
    'footer.social.twitter' => 'Follow us on Twitter',
    'generic.all_city' => '',
    'generic.all_districts' => 'Select a district',
    'generic.all_institution' => '',
    'report.resolved_issue' => '',
    'generic.-in' => 'in',
    'generic.in-district' => 'District',
    'report.resolved_issue.0' => 'Already',
    'report.resolved_issue.1' => 'solved issues in ',
    'comment.placeholder' => 'Tell us your what you think. ',
    'footer.back_to_top' => 'Back to top',
    'footer.follow_us' => 'Follow us',
    'footer.how_it_works' => 'How it works?',
    'footer.join_us.0' => 'Become a volunteer',
    'footer.join_us.1' => 'Join',
    'footer.know_more' => 'Learn more about us',
    'footer.know_more.annual_reports' => 'Financial reports and annual reports',
    'footer.know_more.how' => 'How it works?',
    'footer.know_more.mobile_app' => 'Mobile Application',
    'footer.know_more.statistics' => 'Statistics',
    'footer.know_more.team' => 'Team',
    'footer.know_more.widget' => 'myProject widget',
    'footer.our_partners' => 'Partners',
    'footer.stat.resolved' => 'Reports resolved',
    'footer.stat.title' => 'Our project in numbers',
    'footer.stat.unresolved' => 'Reports waiting to be resolved',
    'footer.stat.users' => 'Locals signed up',
    'footer.support' => 'Donate',
    'footer.write_to_us' => 'Write to us',
    'footer.write_to_us.0' => 'Write to us',
    'footer.write_to_us.1' => 'Get in touch if you have a question about myProject',
    'generic.all' => 'All',
    'generic.all_my_reports' => 'All of your reports',
    'generic.all_reports' => 'All reports',
    'generic.choose' => 'Select',
    'generic.close' => 'Close',
    'generic.email' => 'Email address',
    'generic.follow' => 'Follow',
    'generic.following' => 'Following',
    'generic.login' => 'Login',
    'generic.navigation' => 'Navigation',
    'generic.no' => 'No',
    'generic.password' => 'Password',
    'generic.search' => 'Search',
    'generic.search_in_reports' => 'Search among reports',
    'generic.submit' => 'Submit',
    'generic.toplist' => 'Ranking',
    'generic.toplist.score' => '{score} points',
    'generic.yes' => 'Yes',
    'new_admin' => 'Add Administrator',
    'new_city' => 'Add City',
    'report.generic_information' => 'General information',
    'report.location' => 'Location',
    'report.pictures' => 'Pictures',
    'report.user' => 'User',
    'update_city' => 'Update City',
    'upload.failed' => 'Upload failed',
    'pr_page.create' => 'Create pr page',
    'pr_page_news.create' => 'Create news',
];
