<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'apps.disabled' => '',
    'apps.blog' => 'Blog',
    'cron-log' => '',
    'more_reports' => '',
    'report_list' => 'List of reports',
    'about' => 'About us',
    'admin' => 'Admins',
    'apps' => 'Mobile App',
    'city' => 'Cities',
    'contact' => 'Contact',
    'dropdown.lead' => 'Interested in learning more about us?',
    'dropdown.title' => 'How it works?',
    'featured' => 'Popular reports',
    'featured_more' => 'More popular reports',
    'get_to_know_us' => 'Meet our team',
    'institution' => 'Institutions',
    'pr_page' => 'Pr pages',
    'login' => 'Log in',
    'login_to_view_profile' => 'Log in to view your profile',
    'logout' => 'Log out',
    'new' => 'New reports',
    'new_more' => 'More new reports',
    'new_report' => 'Report a problem',
    'partners' => 'Partners and Sponsors',
    'password' => 'Change password',
    'profile' => 'My Profile',
    'register' => 'Register',
    'report' => 'Reports',
    'report.resolved_issue' => 'Reports listed in',
    'score' => '{score} points',
    'search.all_results' => 'All results',
    'search.no_results' => 'No results.',
    'search.placeholder' => 'Find a report',
    'statistics' => 'Statistics',
    'support' => 'Donate',
    'task' => 'Tasks',
    'team' => 'Team',
    'tos' => 'Terms of Service',
    'user' => 'Users',
    'volunteer' => 'Join',
    'pr_page_news' => 'News',
];
