<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'title.base' => 'myProject',
    'author.content' => 'myProject',
    'description.default' => 'Let us know what needs to be fixed in your city',
    'og.site_name' => 'www.myproject.hu',
    'title.about' => 'About us',
    'title.annual_reports' => 'Financial reports and Annual reports',
    'title.api' => 'API Documentation',
    'title.apps' => 'Mobile Application',
    'title.bureau' => 'Received a letter from us, here\'s how you can answer ',
    'title.contact' => 'Contact',
    'title.default' => 'Let us know what needs to be fixed in your city',
    'title.howitworks' => 'How it works',
    'title.partners' => 'Partners and Sponsors',
    'title.rss' => 'RSS',
    'title.statistics.city' => 'City statistics',
    'title.statistics.index' => 'Statistics',
    'title.statistics.institution' => 'Institution statistics',
    'title.statistics.user' => 'User statistics',
    'title.support' => 'Donate',
    'title.team' => 'Our team',
    'title.tos' => 'Terms of Service',
    'title.volunteer' => 'Volunteer',
];
