<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'news' => ' pr page\'s news',
    'status.active' => 'Active',
    'status.inactive' => 'Inactive',
    'update.title' => 'Title',
    'update.text' => 'Text',
    'update.highlighted' => 'Highlighted',
    'update.published_at' => 'Published at',
    'update.image_file_name' => 'Image',
    'create' => 'Create news',
    'button.upload_image' => 'Upload new image',
    'highlighted' => 'Highlighted news',
    'button.activate' => 'Activate',
    'button.inactivate' => 'Inactivate',
    'button.save_changes' => 'Save changes',
    'button.highlight' => 'Add highlight status',
    'button.undo_highlight' => 'Revert highlighted status',
    'button.more' => 'Show more',
    'confirm.highlight.title' => 'Edit highlighted status',
    'confirm.undo_highlight.confirm.first_part' => 'Are you sure to delete highlighted status of the ',
    'confirm.undo_highlight.confirm.second_part' => ' news?',
    'confirm.highlight.confirm' => 'Are you sure to highlight this news?',
    'confirm.highlight.message.first_part' => 'The previous highlighted news (',
    'confirm.highlight.message.second_part' => ') will loose the highlighted status.',
    'confirm.delete.title' => 'Delete news',
    'confirm.delete.confirm.first_part' => 'Are you sure to delete the ',
    'confirm.delete.confirm.second_part' => ' news?',
];