<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'pr_page' => 'Pr page',
    'update.title' => 'Title',
    'update.introduction' => 'Introduction text',
    'update.info.web_page' => 'Web page',
    'update.info.email' => 'E-mail',
    'update.info.phone' => 'Phone',
    'update.info.address' => 'Address',
    'update.map_status' => 'Map status',
    'update.custom_color' => 'Code of custom_color (eg.: #81bb41)',
    'update.status' => 'Status of the page',
    'update.social_feed_url' => 'Url for social feed (facebook, twitter, instagram)',
    'update.video_url' => 'Url of youtube video',
    'update.cover_file_name' => 'Cover image',
    'update.logo_file_name' => 'Logo image',
    'update.url' => 'The url of the page',
    'update.title.introduction' => 'Introduction',
    'update.title.connection' => 'Connection',
    'update.title.appearance' => 'Appearance and pr details',
    'update.title.map' => 'Map',
    'update.title.settings' => 'Settings, details',
    'map_status.all' => 'All',
    'map_status.in_progress' => 'In progress',
    'map_status.resolved' => 'Resolved',
    'info.web_page' => 'Web page: ',
    'info.email' => 'E-mail: ',
    'info.phone' => 'Phone: ',
    'info.address' => 'Address: ',
    'statistic.resolved_reports' => 'Resolved reports',
    'statistic.response_time' => 'Days of response',
    'statistic.response_time.day' => ' days',
    'statistic.resolved_users_reports' => 'Your solved reports',
    'statistic.in_progress_reports' => 'Reports in progress',
    'map.title.0' => 'All reports',
    'map.title.1' => 'Reports in progress',
    'map.title.2' => 'Resolved reports',
    'button.news' => 'Edit news',
    'button.upload_image' => 'Upload new image',
    'button.send_report' => 'Send report to this institution',
    'title.news' => 'News',
    'confirm.delete.title' => 'Delete pr page',
    'confirm.delete.confirm' => 'Are you sure you want to delete the pr page from the database?',
    'confirm.delete.message' => 'The details and news of the page are deleted.',
    'status.public' => 'Public',
    'status.not_public' => 'Not public',
    'grid.status' => 'Status',
    'grid.created_at' => 'Created at',
    'tooltip.resolved_reports' => 'Jelenleg a szervezetnek ennyi bejelentését tartjuk számon megoldottként a myProject.',
    'tooltip.response_time' => 'A válaszadási időt az olyan bejelentések válaszadási idejének átlaga adja ki, melyekre ez a szervezet már válaszolt és nem volt más illetékes érintett az ügy megoldásában.',
    'tooltip.resolved_users_reports' => 'Ennyi bejelentést küldtél te, amit ennek az illetékesnek küldtünk ki.',
    'tooltip.in_progress_reports' => 'Ennyi bejelentése van a szervezetnek, amelyet már megkapott intézkedésre, de még nem zártuk le megoldott vagy megoldatlan státusszal.',
];