<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'old_password_alert' => '',
    'password_must_be' => '',
    'profile-picture' => '',
    'profile-picture-updated' => '',
    'set_as_password' => '',
    'view_title' => '',
    'manage' => '@@@@',
    'report.set_as_city' => 'Set my city',
    'city_district_filtered_reports' => 'We are showing you the reports from this city and district',
    'menu.drafts' => 'My drafts ({count})',
    'menu.logout' => 'Log out',
    'menu.manage' => 'Edit profile',
    'menu.my_reports' => 'My reports: ({count})',
    'modify_password' => 'Change password',
    'modify_profile' => 'Edit profile',
    'notifications' => 'Notifications',
    'personal_information' => 'Personal information',
    'report.count' => 'report',
    'report.inprogress' => 'in progress',
    'report.solved' => 'solved',
    'report.unsolved' => 'unresolved',
    'save_changes' => 'Save changes',
    'send_frequency' => 'How often',
    'send_notification' => 'Notify me about this',
    'title' => 'My profile',
    'title.drafts' => 'My drafts',
    'top.setCity' => 'Set your city',
    'your_password_must_be' => 'Your password must be:',
];
