<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'update' => 'Edit Rule',
    'create' => 'Add Rule',
    'delete' => 'Delete Rule',
    'delete.message' => 'Are you sure you want to delete this rule fromt he city?',
    'grid.institution' => 'Institution',
    'grid.street_group' => 'Street group',
    'placeholder.category' => 'Pick a category, if necessary',
    'placeholder.district' => 'Pick a district if necessary',
    'placeholder.institution' => 'Select institution',
    'placeholder.street' => 'Add street address if necessary',
    'status.active' => 'Active',
    'status.inactive' => 'Inactive',
    'status.not_public' => 'Not public',
    'status.public' => 'Public',
    'update.email_addresses' => 'Email addresses',
    'update.note' => 'Note:',
];
