<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'no-report-to-assign' => '',
    'no-task-found' => '',
    'activity.answer' => '{institution}\'s reply arrived.',
    'activity.comment' => '{user} commented on: {report}',
    'activity.new_info' => '{user} sent an update.',
    'activity.no_answer' => '{institution} has not answered since {days} days.',
    'activity.no_new_info' => '{user} has not sent any update since {days} days.',
    'activity.no_response' => '{user} has not sent any update since {days} days. ',
    'activity.response' => '{user} sent an update.',
    'activity.incoming_email' => '{institution} sent an email. ',
    'activity.incoming_email_plain' => '{email} contains a response. ',
    'assign.description' => 'This is a response from {from} sent to {to} address. We need to find the report first.',
    'assign.mail.attachment' => 'Attachment',
    'assign.mail.content' => 'Email content',
    'assign.mail.subject' => 'Email subject',
    'assign.placeholder' => 'Find report',
    'assign.title' => 'Attach reply',
    'index.activity' => 'Activity',
    'index.assign' => 'Add to report',
    'index.report' => 'Related report',
    'tab.active' => 'Active reports',
    'tab.comment' => 'New comments',
    'tab.new' => 'New reports',
];
