<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'update.success' => 'Successfully modified.',
    'confirm' => '',
    'delete' => 'Delete User',
    'delete.description' => 'The profile of the user will not be available, reports remain unchanged.',
    'delete.message' => 'Are you sure you want to delete the user from the database?',
    'email-not-unique' => '<p>This email address is already registered.</>
                        <ul class="tooltip__list">
                            <li><a class="link link--info" href="{urlLogin}"> Log in</a> or </li>
                            <li><a class="link link--info" href="{urlRecover}"> Request new password</a>, if you can not remember it.</li>
                        </ul>',
    'form.email' => 'Email address',
    'form.first_name' => 'First Name',
    'form.last_name' => 'Last name',
    'form.new_password' => 'New password',
    'form.old_password' => 'Current password',
    'form.password' => 'Password',
    'form.password_repeat' => 'Repeat password',
    'form.phone_number' => 'Phone number',
    'form.repeat_password' => 'Repeat password',
    'index.full_name' => 'Name',
    'index.reports' => 'Repors',
    'notification.0' => 'No notification.',
    'notification.1' => 'Immediately',
    'notification.1.hint' => 'As soon as any activity is happening with the report.',
    'notification.2' => 'Daily summary',
    'notification.2.hint' => 'Send a summary of activities from the previous day.',
    'notificationtype.1' => 'My reports',
    'notificationtype.1.hint' => 'Reports you sent',
    'notificationtype.2' => 'Reports you follow',
    'notificationtype.2.hint' => 'Reports you follow',
    'report.created_at' => 'Create date',
    'report.institution_name' => 'Institution',
    'report.latitude' => 'Latitude',
    'report.longitude' => 'Longitude',
    'report.new_report' => 'new report',
    'report.report_category_name' => 'Category',
    'report.resolved' => 'solved',
    'report.status' => 'Status',
    'report.unresolved' => 'Unresolved',
    'report.url' => 'Link',
    'report.user_location' => 'Address',
    'report.waiting_for_answer' => 'Waiting for response',
    'report.waiting_for_response' => 'Waiting for update',
    'report.waiting_for_solution' => 'Solved',
    'status.active' => 'Active',
    'status.inactive' => 'Inactive',
    'update.api' => 'API',
    'update.password_change' => 'Change password',
    'update.personal_info' => 'Personal data',
    'update.report' => 'report',
    'update.reports' => 'Reports',
    'update.upload' => 'Upload new photo',
    'kill.message' => 'All reports, comments, user data, report activities and ratings will be deleted without the chance of restoring. ARE YOU SURE???',
];
