<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'title' => 'Widgets',
    'lead' => 'Help us spread the word by embedding our widget',
    'what_is_widget.title' => 'What\'s a widget?',
    'what_is_widget.description' => 'A web widget is a small piece of code that is easy to publish on a website or blog.',
    'share_with_code' => 'With this code you can publish our widgets on your site:',
];

